export const COUNTRY_CODES: Record<string, string> = {
  Algeria: 'dz',
  Argentina: 'ar',
  Australia: 'au',
  Austria: 'at',
  Belgium: 'be',
  Bolivia: 'bo',
  Bosnia: 'ba',
  'Bosnia and Herzegovina': 'ba',
  Brazil: 'br',
  Cameroon: 'cm',
  Canada: 'ca',
  'Cape Verde': 'cv',
  'Cape Verde Islands': 'cv',
  Chile: 'cl',
  Colombia: 'co',
  'Congo DR': 'cd',
  'Congo Democratic Republic': 'cd',
  'Costa Rica': 'cr',
  Croatia: 'hr',
  Curacao: 'cw',
  Czechia: 'cz',
  'Czech Republic': 'cz',
  Denmark: 'dk',
  Ecuador: 'ec',
  Egypt: 'eg',
  England: 'gb-eng',
  France: 'fr',
  Germany: 'de',
  Ghana: 'gh',
  Greece: 'gr',
  Haiti: 'ht',
  Hungary: 'hu',
  Iran: 'ir',
  Iraq: 'iq',
  Italy: 'it',
  'Ivory Coast': 'ci',
  Japan: 'jp',
  Jordan: 'jo',
  Kuwait: 'kw',
  Mexico: 'mx',
  Morocco: 'ma',
  Netherlands: 'nl',
  'New Zealand': 'nz',
  Nigeria: 'ng',
  Norway: 'no',
  Panama: 'pa',
  Paraguay: 'py',
  Peru: 'pe',
  Poland: 'pl',
  Portugal: 'pt',
  Qatar: 'qa',
  Romania: 'ro',
  'Saudi Arabia': 'sa',
  Scotland: 'gb-sct',
  Senegal: 'sn',
  Serbia: 'rs',
  Slovakia: 'sk',
  Slovenia: 'si',
  'South Africa': 'za',
  'South Korea': 'kr',
  Spain: 'es',
  Sweden: 'se',
  Switzerland: 'ch',
  Tunisia: 'tn',
  Turkey: 'tr',
  Turkiye: 'tr',
  'United Arab Emirates': 'ae',
  Uruguay: 'uy',
  Uzbekistan: 'uz',
  Venezuela: 've',
  USA: 'us',
  'United States': 'us',
  Wales: 'gb-wls',
};

const FLAG_CODE_ALIASES: Record<string, string> = {
  alg: 'dz',
  arg: 'ar',
  aus: 'au',
  aut: 'at',
  bel: 'be',
  bih: 'ba',
  bol: 'bo',
  bos: 'ba',
  bra: 'br',
  cmr: 'cm',
  cam: 'cm',
  can: 'ca',
  chi: 'cl',
  civ: 'ci',
  col: 'co',
  cod: 'cd',
  congodr: 'cd',
  congodemocraticrepublic: 'cd',
  democraticrepublicofthecongo: 'cd',
  crc: 'cr',
  cro: 'hr',
  cuw: 'cw',
  curacao: 'cw',
  cze: 'cz',
  den: 'dk',
  ecu: 'ec',
  egy: 'eg',
  eng: 'gb-eng',
  fra: 'fr',
  ger: 'de',
  gha: 'gh',
  gre: 'gr',
  hai: 'ht',
  haiti: 'ht',
  hun: 'hu',
  irn: 'ir',
  irq: 'iq',
  ita: 'it',
  jpn: 'jp',
  jor: 'jo',
  kuw: 'kw',
  mex: 'mx',
  mar: 'ma',
  ned: 'nl',
  nga: 'ng',
  nor: 'no',
  nzl: 'nz',
  pan: 'pa',
  par: 'py',
  per: 'pe',
  pol: 'pl',
  por: 'pt',
  qat: 'qa',
  rou: 'ro',
  ksa: 'sa',
  sco: 'gb-sct',
  sen: 'sn',
  srb: 'rs',
  swe: 'se',
  sweden: 'se',
  svk: 'sk',
  svn: 'si',
  kor: 'kr',
  rsa: 'za',
  esp: 'es',
  sui: 'ch',
  tun: 'tn',
  tur: 'tr',
  uae: 'ae',
  uru: 'uy',
  ury: 'uy',
  usa: 'us',
  uzb: 'uz',
  ven: 've',
  wal: 'gb-wls',
  cpv: 'cv',
  england: 'gb-eng',
  scotland: 'gb-sct',
  wales: 'gb-wls',
  unitedstates: 'us',
  'saudiarabia': 'sa',
  'southkorea': 'kr',
  'netherlands': 'nl',
  bosnia: 'ba',
  bosniaandherzegovina: 'ba',
  bosniaherzegovina: 'ba',
  capeverde: 'cv',
  capeverdeislands: 'cv',
  czechia: 'cz',
  czechrepublic: 'cz',
  egypt: 'eg',
  iran: 'ir',
  iriran: 'ir',
  ivorycoast: 'ci',
  cotedivoire: 'ci',
  korearepublic: 'kr',
  newzealand: 'nz',
  southafrica: 'za',
  turkiye: 'tr',
  turkey: 'tr',
  unitedarabemirates: 'ae',
};

function normalizeFlagKey(value: string): string {
  return value
    .trim()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '');
}

export function resolveFlagCode(teamNameOrCode: string): string {
  const trimmed = teamNameOrCode.trim();
  if (!trimmed) return 'us';

  const directMatch = COUNTRY_CODES[trimmed];
  if (directMatch) return directMatch;

  const normalized = normalizeFlagKey(trimmed);
  const aliasMatch = FLAG_CODE_ALIASES[normalized];
  if (aliasMatch) return aliasMatch;

  const normalizedWithHyphens = trimmed.toLowerCase().replace(/[\s_]+/g, '-');
  return normalizedWithHyphens;
}

export function getFlagUrl(teamNameOrCode: string): string {
  const code = resolveFlagCode(teamNameOrCode);
  return `https://flagcdn.com/w160/${code}.png`;
}
